image: Visual Studio 2019

version: 0.5.6+appveyor.{build}

init:
  - dotnet --info
  - git config --global core.autocrlf true

configuration: release

build_script:
  - dotnet build src\LocalAppVeyor.Engine --configuration %configuration%
  - dotnet build src\LocalAppVeyor --configuration %configuration%

after_build:
  - dotnet pack src\LocalAppVeyor.Engine --configuration %configuration% --output out_engine
  - dotnet pack src\LocalAppVeyor --configuration %configuration% --output out_console

test_script:
  - dotnet test tests\LocalAppVeyor.Engine.UnitTests\LocalAppVeyor.Engine.UnitTests.csproj --configuration %configuration%

artifacts:
  - path: out_engine\*.nupkg
    name: engine_packages
  - path: out_console\*.nupkg
    name: console_packages

deploy:
  - provider: NuGet
    api_key: 
      secure: pfqzF7PjoXrSNEgCLSg83XLUKoxoxwkJdcQGC9Eev/zemvGt2LqpVs6yWsN2yuK9
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: engine_packages

  - provider: NuGet
    api_key: 
      secure: FMGFZeEPpDdvqIwKxc+K1pb9XNimloBN/VA4gf5i9KvcbTHR/c8RCXJimf0/yCII
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: console_packages