image: Visual Studio 2022

version: 0.6.0+appveyor.{build}

init:
  - dotnet --info
  - git config --global core.autocrlf true

configuration: release

build_script:
  - dotnet build src\LocalAppVeyor.Engine --configuration %configuration%
  - dotnet build src\LocalAppVeyor --configuration %configuration%

after_build:
  - dotnet pack src\LocalAppVeyor.Engine --configuration %configuration% --output out_engine
  - dotnet pack src\LocalAppVeyor --configuration %configuration% --output out_console

test_script:
  - dotnet test tests\LocalAppVeyor.Engine.UnitTests\LocalAppVeyor.Engine.UnitTests.csproj --configuration %configuration%

artifacts:
  - path: out_engine\*.nupkg
    name: engine_packages
  - path: out_console\*.nupkg
    name: console_packages

deploy:
  - provider: NuGet
    api_key: 
      secure: 44crHq8PCXTO+ybHAUJjVHOT0PvFsqlcWH/m+/htVFXHihsmYj22WMnz1NBsDXWR
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: engine_packages

  - provider: NuGet
    api_key: 
      secure: c1ZZc9Hqh92gxYb1pskP22xA+ppb5a3KQ6rESYDJnTn5jZv9PBjfxaRlDtWs765F
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: console_packages