name: Build

on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.os }} (${{ matrix.dotnet }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: ['3.1.201']

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
    
      - run: dotnet build --configuration Release
